module.exports = {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/app/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // RED - Bordeau
        "red-100": "var(--red-100)",
        "red-200": "var(--red-200)",
        "red-300": "var(--red-300)",
        "red-400": "var(--red-400)",
        "red-500": "var(--red-500)",
        "red-600": "var(--red-600)",
        "red-700": "var(--red-700)",
        "red-800": "var(--red-800)",
        "red-900": "var(--red-900)",

        // PINK
        "pink-100": "var(--pink-100)",
        "pink-200": "var(--pink-200)",
        "pink-300": "var(--pink-300)",
        "pink-400": "var(--pink-400)",
        "pink-500": "var(--pink-500)",
        "pink-600": "var(--pink-600)",
        "pink-700": "var(--pink-700)",
        "pink-800": "var(--pink-800)",
        "pink-900": "var(--pink-900)",

        // BEIGE
        "beige-100": "var(--beige-100)",
        "beige-200": "var(--beige-200)",
        "beige-300": "var(--beige-300)",
        "beige-400": "var(--beige-400)",
        "beige-500": "var(--beige-500)",
        "beige-600": "var(--beige-600)",
        "beige-700": "var(--beige-700)",
        "beige-800": "var(--beige-800)",
        "beige-900": "var(--beige-900)",

        // GREEN
        "green-100": "var(--green-100)",
        "green-200": "var(--green-200)",
        "green-300": "var(--green-300)",
        "green-400": "var(--green-400)",
        "green-500": "var(--green-500)",
        "green-600": "var(--green-600)",
        "green-700": "var(--green-700)",
        "green-800": "var(--green-800)",
        "green-900": "var(--green-900)",

        // GREY
        "grey-0": "var(--grey-0)",
        "grey-50": "var(--grey-50)",
        "grey-100": "var(--grey-100)",
        "grey-150": "var(--grey-150)",
        "grey-200": "var(--grey-200)",
        "grey-300": "var(--grey-300)",
        "grey-400": "var(--grey-400)",
        "grey-500": "var(--grey-500)",
        "grey-600": "var(--grey-600)",
        "grey-700": "var(--grey-700)",
        "grey-800": "var(--grey-800)",
        "grey-850": "var(--grey-850)",
        "grey-900": "var(--grey-900)",
        "grey-950": "var(--grey-950)",
        "grey-1000": "var(--grey-1000)",

        // ALIASES
        "primary": "var(--red-500)",
        "secondary": "var(--pink-500)",
        "main-bordeau": "var(--red-500)",
        "main-pink": "var(--pink-500)",
        "main-beige": "var(--beige-500)",
        "main-green": "var(--green-500)",
        "brand": "var(--red-500)",
        "cta": "var(--green-500)",
        "tertiary": "var(--beige-500)",

        // STATE & COMPONENT COLORS
        "border-buttons-error-error": "var(--red-500)",
        "surface-elevation-beige": "#665D4DA6",
        "surface-elevation-grey": "#202020A6",
        "surface-elevation-black": "#101010A6",
        "background-default": "var(--grey-0)",
        "bg-shapes-primary": "var(--red-500)",
        "bg-shapes-secondary": "var(--red-100)",
        "border-buttons-primary-default": "var(--green-200)",
        "border-buttons-primary-hover": "var(--green-400)",
        "border-buttons-primary-active": "var(--green-500)",
        "border-buttons-secondary-default": "var(--green-200)",
        "border-buttons-secondary-hover": "var(--green-300)",
        "border-buttons-secondary-active": "var(--green-300)",
        "border-neutral": "var(--grey-950)",
        "border-inverted": "var(--grey-100)",
        "border-beige": "var(--beige-700)",
        "border-chips-brown-default": "var(--beige-600)",
        "border-chips-brown-hover": "var(--beige-700)",
        "border-chips-brown-selected": "var(--beige-800)",
        "border-chips-pink-default": "var(--pink-200)",
        "border-chips-pink-hover": "var(--pink-400)",
        "border-chips-pink-selected": "var(--pink-500)",
        "border-chips-red-default": "var(--red-200)",
        "border-chips-red-hover": "var(--red-400)",
        "border-chips-red-selected": "var(--red-500)",
        "border-states-active": "var(--red-300)",
        "border-states-default": "var(--red-100)",
        "border-states-disabled": "var(--grey-200)",
        "border-states-error": "var(--red-500)",
        "border-states-hover": "var(--red-200)",
        "border-red": "var(--red-500)",
        "border-pink": "var(--pink-600)",
        "border-states-information": "var(--beige-600)",
        "border-states-success": "var(--green-200)",
        "text-brand": "var(--pink-600)",
        "surface-default": "var(--grey-100)",
        "surface-buttons-primary-default": "var(--green-200)",
        "surface-buttons-primary-hover": "var(--green-400)",
        "surface-buttons-primary-active": "var(--green-500)",
        "surface-buttons-secondary-default": "var(--grey-50)",
        "surface-buttons-secondary-hover": "var(--green-100)",
        "surface-buttons-secondary-active": "var(--green-300)",
        "surface-chips-red-default": "var(--red-200)",
        "surface-states-active": "var(--grey-100)",
        "surface-states-default": "var(--grey-100)",
        "surface-states-disabled": "var(--grey-100)",
        "surface-states-error": "var(--red-200)",
        "surface-states-hover": "var(--grey-100)",
        "surface-states-information": "var(--beige-600)",
        "surface-states-selected": "var(--red-100)",
        "surface-states-success": "var(--green-600)",
        "surface-chips-red-hover": "var(--red-400)",
        "surface-chips-red-selected": "var(--red-500)",
        "surface-chips-pink-default": "var(--pink-200)",
        "surface-chips-pink-hover": "var(--pink-400)",
        "surface-chips-pink-selected": "var(--pink-500)",
        "surface-chips-Brown-default": "var(--beige-600)",
        "surface-chips-Brown-hover": "var(--beige-700)",
        "surface-chips-Brown-selected": "var(--beige-800)",
        "surface-light-beige": "var(--beige-200)",
        "surface-beige": "var(--beige-500)",
        "surface-red": "var(--red-100)",
        "icon-default": "var(--grey-950)",
        "icon-disabled": "var(--grey-500)",
        "icon-on-surface-default": "var(--grey-950)",
        "icon-on-surface-disabled": "var(--grey-500)",
        "icon-on-surface-inverted": "var(--grey-50)",
        "icon-on-surface-beige": "var(--beige-600)",
        "icon-on-surface-red": "var(--red-500)",
        "icon-on-surface-pink": "var(--pink-600)",
        "icon-on-surface-error": "var(--red-500)",
        "icon-on-surface-information": "var(--beige-600)",
        "icon-on-surface-success": "var(--green-600)",
        "icon-inverted": "var(--grey-50)",
        "icon-beige": "var(--beige-600)",
        "icon-red": "var(--red-500)",
        "icon-pink": "var(--pink-600)",
        "icon-error": "var(--red-500)",
        "icon-information": "var(--beige-600)",
        "icon-success": "var(--green-600)",
        "text-default": "var(--grey-950)",
        "text-disabled": "var(--grey-500)",
        "text-error": "var(--red-500)",
        "text-information": "var(--beige-600)",
        "text-inverted": "var(--grey-50)",
        "text-success": "var(--green-600)",
        "text-warning": "var(--red-300)",
        "text-link-default": "var(--green-500)",
        "text-link-visited": "var(--green-700)",
        "text-on-surface-default": "var(--grey-950)",
        "text-on-surface-disabled": "var(--grey-500)",
        "text-on-surface-error": "var(--red-500)",
        "text-on-surface-inverted": "var(--grey-50)",
        "text-on-surface-information": "var(--beige-300)",
        "text-on-surface-success": "var(--green-600)",
        "text-on-surface-brand": "var(--pink-600)"
      },
      spacing: {
        "sizing-positive-0": "var(--sizing-positive-0)",
        "sizing-positive-0.06": "var(--sizing-positive-006)",
        "sizing-positive-0.125": "var(--sizing-positive-0125)",
        "sizing-positive-0.25": "var(--sizing-positive-025)",
        "sizing-positive-0.375": "var(--sizing-positive-0375)",
        "sizing-positive-0.5": "var(--sizing-positive-05)",
        "sizing-positive-0.75": "var(--sizing-positive-075)",
        "sizing-positive-1": "var(--sizing-positive-1)",
        "sizing-positive-1.25": "var(--sizing-positive-125)",
        "sizing-positive-1.5": "var(--sizing-positive-15)",
        "sizing-positive-1.75": "var(--sizing-positive-175)",
        "sizing-positive-2": "var(--sizing-positive-2)",
        "sizing-positive-2.5": "var(--sizing-positive-25)",
        "sizing-positive-2.75": "var(--sizing-positive-275)",
        "sizing-positive-3": "var(--sizing-positive-3)",
        "sizing-positive-3.25": "var(--sizing-positive-325)",
        "sizing-positive-3.5": "var(--sizing-positive-35)",
        "sizing-positive-4": "var(--sizing-positive-4)",
        "sizing-positive-4.25": "var(--sizing-positive-425)",
        "sizing-positive-4.5": "var(--sizing-positive-45)",
        "sizing-positive-4.75": "var(--sizing-positive-475)",
        "sizing-positive-5": "var(--sizing-positive5)",
        "sizing-negative-0.06":  "var(--sizing-negative-006)",
        "sizing-negative-0.125": "var(--sizing-negative-0125)",
        "sizing-negative-0.25": "var(--sizing-negative-025)",
        "sizing-negative-0.375": "var(--sizing-negative-0375)",
        "sizing-negative-0.5": "var(--sizing-negative-05)",
        "sizing-negative-0.75": "var(--sizing-negative-075)",
        "sizing-negative-1": "var(--sizing-negative-1)",
        "sizing-negative-1.25": "var(--sizing-negative-125)",
        "sizing-negative-1.5": "var(--sizing-negative-15)",
        "sizing-negative-1.75": "var(--sizing-negative-175)",
        "sizing-negative-2": "var(--sizing-negative-2)",
        "sizing-negative-2.5": "var(--sizing-negative-25)",
        "sizing-negative-2.75": "var(--sizing-negative-275)",
        "sizing-negative-3": "var(--sizing-negative-3)",
        "spacing-positive-empty": "var(--sizing-positive-0)",
        "spacing-positive-xxxs": "var(--sizing-positive-0.125)",
        "spacing-positive-xxs": "var(--sizing-positive-0.25)",
        "spacing-positive-xs": "var(--sizing-positive-0.375)",
        "spacing-positive-sm": "var(--sizing-positive-0.5)",
        "spacing-positive-m": "var(--sizing-positive-0.75)",
        "spacing-positive-md": "var(--sizing-positive-1)",
        "spacing-positive-lg": "var(--sizing-positive-1.5)",
        "spacing-positive-xl": "var(--sizing-positive-2)",
        "spacing-positive-xxl": "var(--sizing-positive-2.5)",
        "spacing-positive-xxxl": "var(--sizing-positive-3)",
        "border-default": "var(--sizing-positive-0.125)",
        "border-focused": "var(--sizing-positive-0.125)",
        "border-selected": "var(--sizing-positive-0.25)",
        "radius-square": "var(--sizing-positive-0)",
        "radius-xs": "var(--sizing-positive-0.125)",
        "radius-s": "var(--sizing-positive-0.25)",
        "radius-m": "var(--sizing-positive-0.5)",
        "radius-lg": "var(--sizing-positive-0.75)",
        "radius-round": "var(--sizing-positive-5)",
        "spacing-negative-xxxs": "var(--sizing-negative-0.125)",
        "spacing-negative-xxs": "var(--sizing-negative-0.25)",
        "spacing-negative-xs": "var(--sizing-negative-0.375)",
        "spacing-negative-sm": "var(--sizing-negative-0.5)",
        "spacing-negative-m": "var(--sizing-negative-0.75)",
        "spacing-negative-md": "var(--sizing-negative-1)",
        "spacing-negative-lg": "var(--sizing-negative-1.5)",
        "spacing-negative-xl": "var(--sizing-negative-2)",
        "spacing-negative-xxl": "var(--sizing-negative-2.5)",
        "spacing-negative-xxxl": "var(--sizing-negative-3)"
      },
      fontSize: {
        "xs": ["var(--Heading-XS)", { lineHeight: "var(--height-Heading)" }],
        "sm": ["var(--Heading-S)", { lineHeight: "var(--height-Heading)" }],
        "base": ["var(--Body-s)", { lineHeight: "var(--height-Body)" }],
        "lg": ["var(--Body-sm)", { lineHeight: "var(--height-Body)" }],
        "xl": ["var(--Body-m)", { lineHeight: "var(--height-Body)" }],
        "2xl": ["var(--Heading-M)", { lineHeight: "var(--height-Heading)" }],
        "3xl": ["var(--Heading-L)", { lineHeight: "var(--height-Heading)" }],
        "4xl": ["var(--Heading-XL)", { lineHeight: "var(--height-Heading)" }],
        "5xl": ["var(--Heading-XXL)", { lineHeight: "var(--height-Heading)" }],
      },
      fontFamily: {
        'body': ['Dongle', 'sans-serif'],
        'heading': ['Dongle', 'sans-serif'],
      },
      fontWeight: {
        'light': '300',
        'regular': '400',
        'bold': '700',
      },
      borderRadius: {
        "none": "var(--radius-square)",
        "xs": "var(--radius-xs)",
        "sm": "var(--radius-s)",
        "md": "var(--radius-m)",
        "lg": "var(--radius-lg)",
        "full": "var(--radius-round)",
      },
      borderWidth: {
        "DEFAULT": "var(--border-default)",
        "focused": "var(--border-focused)",
        "selected": "var(--border-selected)",
      },
    },
  },
  plugins: [],
}